### ISSUE TITLE
Shoud we rename schema files to *.json?

### ISSUE THREAD

**Issue by jpmens** [owntracks/json-schema#1]
Might it be worth our while to name schema files `*.json` so as to show what's in them? Might also be important when serving these over HTTP so a Web server can set MIME type accordingly.

**Comment by ckrey** [comment]
naming the files and linking (referring to) the schemas is not trivial. I was not successfull while the schemas had a `.json` suffix. In all the examples there is no suffix

**Comment by ckrey** [comment]
Not sure what is best practise for file naming, $id, etc.
https://stackoverflow.com/questions/70807993/are-there-recommended-ways-to-structure-multiple-json-schemas
